### ISSUE TITLE
Maybe a "correction" for Chapter 2 Graphs

### ISSUE THREAD

**Issue by Kronen** [AllenDowney/ThinkComplexity2#21]
I don't know what is your preferred way to get those kind of corrections/typos, so I posted it here.

In Chapter 2 Graphs you say

> We can use reachable_nodes to write is_connected:

```
def is_connected(G):
    start = next(G.nodes_iter())
    reachable = reachable_nodes(G, start)
    return len(reachable) == len(G)
```

> is_connected chooses a starting node by calling nodes_iter, which returns an iterator object, and passing the result to next, which returns the first node.

> **seen** gets the set of nodes that can be reached from start. If the size of this set is the same as the size of the graph, that means we can reach all nodes, which means the graph is connected.

You say **_seen_** when I think you should say **_reachable_**, because _seen_ is the returned variable from _reachable_node_ function which in turns gets assigned to _reachable_. But you are explaining now the function _is_connected_ not the function _reachable_nodes_.

**Comment by AllenDowney** [comment]
Fixed.  Thank you!
