### ISSUE TITLE
PDF (continuous) plot being used for PMFs

### ISSUE THREAD

**Issue by gwtaylor** [AllenDowney/ThinkComplexity2#23]
I wasn't sure if it was intentional that you're using `thinkplot.Pdf` instead of `thinkplot.Pmf` for the analysis in Chapter 4. This is in section 4.3, e.g.

```python
thinkplot.Pdf(pmf_fb, label= Facebook )
thinkplot.Pdf(pmf_ws, label= WS graph )
```
It makes more sense to me to use `thinkplot.Pmf` since we are dealing with discrete quantities.

**Comment by AllenDowney** [comment]
That is deliberate.  If the PMF is smooth enough, it sometimes look better to plot it as a PDF.
