### ISSUE TITLE
Turing diffusion model

### ISSUE THREAD

**Issue by gwtaylor** [AllenDowney/ThinkComplexity2#25]
The beginning of section 7.1 discusses Turing's diffusion model:

_In 1952 Alan Turing published a paper called “The chemical basis of morpho- genesis”, which describes the behavior of systems involving two chemicals that diffuse in space and react with each other._

It then branches to talk about a CA-based version

_Turing’s model is based on differential equations, but it can also be imple- mented using a cellular automaton.
But before we get to Turing’s model, we’ll start with something simpler: a diffusion system with just one chemical._

The way it's written implies returning to Turing's DE-based model, but the chapter never returns to discuss this.

**Comment by AllenDowney** [comment]
I think it says we'll get back to Turing's model, which we do.  Granted, we get back to the CA implementation, not the DE implementation.  So I will see if there's a good way to clarify that.
