### ISSUE TITLE
Dead links in Appendix Exercise A.6

### ISSUE THREAD

**Issue by gwtaylor** [AllenDowney/ThinkComplexity2#35]
The Appendix Exercise A.6 provides some dead links:

> You can download my map implementations from \url{thinkcomplex.com/Map.py}, and the code I used in this section from \url{thinkcomplex.com/listsum.py}.

**Comment by AllenDowney** [comment]
I fixed that by removing the appendix :)

As it happens, this appendix in Think Complexity is an early version of the one that is now in Think Python.  I think it makes more sense there, so I am removing it here.
