### ISSUE TITLE
Notre Dame web graph data link is dead (Exercise 4.3)

### ISSUE THREAD

**Issue by gwtaylor** [AllenDowney/ThinkComplexity2#36]
The link to the Data files from the Barabasi and Albert paper in Exercise 4.3 no longer works:
http://www3.nd.edu/~networks/resources.htm

It looks like SNAP is maintaining one of the Notre Dame datasets, but not the IMDB Actors dataset:
https://snap.stanford.edu/data/web-NotreDame.html

A quick look doesn't turn up an appropriate place to re-direct, so possibly remove the link or contact Barabasi's group at Northeastern.

**Comment by AllenDowney** [comment]
I've added a link to the Internet Archive.  Thanks!
