### ISSUE TITLE
Make the stochastic experiments reproducible with a seed

### ISSUE THREAD

**Issue by drvinceknight** [AllenDowney/ThinkComplexity2#40]
There are numerous stochastic experiments in the book/notebooks. Would it be worthwhile setting a seed for them?

I believe all stochastic operations are done in `numpy` so the following would suffice for each experiment:

```
np.random.seed(0)
```

(
for repeated experiments I often use 

```
for seed in range(number_repetitions):
    np.random.seed(seed)
    ...
```
)

This ensures reproducibility of results.

- For the reader it would ensure they get the exact same images etc as in the book;
- It's a good habit for potential research/grad students using the book.

Just a suggestion :)

**Comment by AllenDowney** [comment]
Yes, this is a good idea.  I usually don't do it during development, so each time I do a test run I see a different result.  That can help me avoid latching on to a particular run that might not be typical.

**Comment by AllenDowney** [comment]
Done!
