### ISSUE TITLE
Using itertools for `make_all_agents` in chapter 11

### ISSUE THREAD

**Issue by drvinceknight** [AllenDowney/ThinkComplexity2#41]
Currently the `make_all_agents` function in chapter 11 makes use of binary arithmetic:

```
def make_all_agents(fit_land, agent_maker):
    """Make an array of Agents.
    
    fit_land: FitnessLandscape
    agent_maker: class used to make Agent
    
    returns: array of Agents
    """
    N = fit_land.N
    xs = np.arange(2**N)
    ys = 2**np.arange(N)[::-1]    
    locs = np.bitwise_and.outer(xs, ys) > 0
    agents = [agent_maker(loc, fit_land) for loc in locs]
    return np.array(agents)
```

> make_all_agents uses the outer product of bitwise_and, which is not the most obvious operation. 

Would using `itertools.product` (which returns the product of any set of spaces) make this more readable/obvious? 

```
def make_all_agents(fit_land, agent_maker):
    """Make an array of Agents.
    
    fit_land: FitnessLandscape
    agent_maker: class used to make Agent
    
    returns: array of Agents
    """
    locations =  itertools.product([0, 1], repeat=fit_land.N)
    agents = [agent_maker(loc, fit_land) for loc in locations]
    return np.array(agents)
```

(`itertools.product(S, repeat=N)` creates a generator that gives the elements of $S^N$)

Currently `make_all_agents` is not included in the text of the book. This is understandable given the slightly complex use of binary arithmetic, perhaps using `itertools` would allow for it to be included.

Just a suggestion :)

(Note that that that particular implementation creates tuples of 0/1 and not lists of True/False, this could be refactored.)

(A **very** minor further suggestion would be to also use the variable name `agent_class` instead of `agent_maker`, I spent a little while looking around for some sort of factory function but that could well be a very personal miss read).

**Comment by AllenDowney** [comment]
Good suggestion.  I'll make this change when I have a chance.

Thanks!

**Comment by AllenDowney** [comment]
Done 89b782e4b189cd1fdaeab5638c8b2f2a8cfb1e3f

Thanks again.
